### ISSUE TITLE
Can I run it behind proxy

### ISSUE THREAD

**Issue by jasper2virtual** [agis/mcdetect#14]
Hello, mcdetect is great. I love it.
But can I run it behind proxy. as my office connect to internet by proxy server.

**Comment by agis** [comment]
That'd require configuring the Chrome/Chromium instance to use a proxy. I don't know how this is done, but with a little search I've found https://blog.apify.com/how-to-make-headless-chrome-and-puppeteer-use-a-proxy-server-with-authentication-249a21a79212 which might help you.
