### ISSUE TITLE
SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by mengio001** [agis/mcdetect#5]
Hi, I have a Syntax Error when i'm trying to run the script. Can you look at it or do I something wrong? First of all thanks for the solution and as second thanks for the feedback. For more info look attachment.

Attachment: https://1drv.ms/i/s!Ap-6dK_njayli2Mdgi7WwxQ6Xwxk

**Comment by agis** [comment]
Hello.

mcdetect requires node 7.6.0 or later. What is your node version?

**Comment by mengio001** [comment]
Thanks for your reply. Indeed I had node version 6.1. I have upgraded now and its works fine.

**Comment by agis** [comment]
Nice, closing this.
