### ISSUE TITLE
Can't test a site - UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by akarasev** [agis/mcdetect#7]
Hello!

It's a great tool, but, unfortunately, I can't use is to the following errors. Would you fix this please?

> $ node -v && npm -v && mcdetect example.org
v8.9.4
5.6.0
(node:21616) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: kill ESRCH
(node:21616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by agis** [comment]
Thanks for reporting this! I've pushed a new version (1.0.5), can you try it?

**Comment by akarasev** [comment]
Thank you for the fast response. Unfortunately, the new version `1.0.5` has the same output.

**Comment by agis** [comment]
I think this is actually https://github.com/GoogleChrome/puppeteer/issues/1813. Did you install puppeteer as root?

**Comment by akarasev** [comment]
I didn't, but `npm` shows it as dependency:
> $ npm -g ls --depth=1                                                                                                                     
> /home/akarasev/.nvm/versions/node/v8.9.4/lib
> ├─┬ mcdetect@1.0.5
> │ ├── chalk@2.3.0
> │ ├── puppeteer@1.0.0
> │ └── yargs@8.0.2

**Comment by agis** [comment]
I'm not really familiar with the JS ecosystem so can't actually help much with this. A better place to get help would be the original issue I linked above.
